services:
  forecast_cron:
    build: ./forecast_cron
    depends_on:
      - forecast
    networks:
      - default
  weather:
    build: ./weather_service
    ports:
      - "8001:8001"
    env_file:
      - .env

  forecast:
    build: ./forecast_service
    ports:
      - "8002:8002"
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  trading:
    build: ./trading_service
    ports:
      - "8003:8003"

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - weather
      - forecast
      - trading
